// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"400","screenHeight":"300","changeWindowWidthTo":"400","changeWindowHeightTo":"500","renderingMode":"auto","alwaysDash":"off"}},
{"name":"AutoLoad","status":true,"description":"タイトル画面仕様変更プラグイン","parameters":{"効果音演奏":"false","タイトルスキップポリシー":"2","タイトルマップID":"0"}},
{"name":"OnlineAvatar","status":false,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyBpQUp50qPnVOhPk2xDznNcMImUcH2XSwo","authDomain":"motizukikoumuten.firebaseapp.com","databaseURL":"https://motizukikoumuten-default-rtdb.firebaseio.com","avatarEvent":"0","syncSwitchStart":"11","syncSwitchEnd":"20","syncVariableStart":"11","syncVariableEnd":"20"}},
{"name":"UTSU_DisableImageSmoothing","status":true,"description":"画像の拡大時の補完機能を無効にします","parameters":{}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"true","ピクチャ番号の変数番号":"0","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"false","戦闘中常にコモン実行":"false","無効スイッチ":"0"}},
{"name":"HyperLink","status":true,"description":"ゲーム中に外部ページへのリンクを貼ります。","parameters":{"description":""}},
{"name":"Oggy_CustomLoading","status":true,"description":"v1.00 This plugin customizes a loading ui","parameters":{}},
{"name":"kaihen","status":true,"description":"","parameters":{}},
{"name":"HyperLink2","status":true,"description":"ゲーム中に外部ページへのリンクを貼ります。","parameters":{"description":""}},
{"name":"InputForm","status":true,"description":"フォーム作って文字入力（修正版）","parameters":{}},
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"最初のセルに戻る":"true"}}
];
